### ISSUE TITLE
Enhancement: Create GitHub CI/CD workflow and/or client side commit hooks

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/temp-test-ioccc#2537] opened 2024-07-02 12:54 UTC
The generation of the `.html` files from markdown should be part of a GitHub CI/CD workflow to avoid having to do this manually.  Each push to GitHub would apply the necessary Makefile targets.

**Comment by lcn2** [comment] 2024-07-02 23:42
FYI @SirWumpus: We mark comments with 👀 to remind ourselves and to mark that we are pondering the contents.

**Comment by lcn2** [comment] 2024-07-03 07:31
> The generation of the .html files from markdown should be part of a GitHub CI/CD workflow to avoid having to do this manually.

The question we have been asking is: Why?  That is why is it important to avoid having to do this manually **FOR THIS REPO**.

We might see the value of client side and/or server side CI/CD workflow.  We might see the value of this for a product with lots of contributors and/or a fair rate of pull requests.  

That is not where we are now with **THIS REPO** and that certainly will **NOT** be the case after the **Great Fork Merge**.

After the **Great Fork Merge**, the [Official IOCCC winner website](https://www.ioccc.org) will be slow to change. We hope, after perhaps an initial brief burst to correct problems we might encounter after the merge, to update the website perhaps every other month or so: certainly a **MUCH SLOWER CHURN RATE** than has happened in this repo by orders of magnitude. 

Only the IOCCC judges will ever update the winner repo.  And it will likely fall on Landon Noll to perform the updates.

- [ ] At present there are tools that process the web site. Those actions, driven by a single make command, take about 6 to 10 minutes to run. And the result is viewed on a local web server all before the commit is executed to make the result public.  That is, the build and test is executed **BEFORE** a commit is even done and the result is examined locally before the git commit is even executed.  

Adding client side commit hooks so perform the same tests and functions doesn't seem to be an advantage and only duplicates that is done already.  Enforcing it on the client side or on the server side doesn't seem to gain us much either. 

After the **Great Fork Merge**, the [Official IOCCC winner website](https://www.ioccc.org) will probably be updated by one person who already follows a procedure even before a git commit is even done. 

We wonder if it is worth the delay in starting IOCCC28 to retool the procedure just to automatically run actions on the client or server side?

For all of the above reasons, and perhaps a few more, we are tempted to close this issue with a "won't fix". 

But we will sleep on it .. and return to writing some code that is in the critical path of starting IOCCC28 .. and then return to this matter and see if anything has come forward to change our position.

**Comment by xexyl** [comment] 2024-07-03 11:21
I also am wondering the value here and for the same reasons. What could the client side hook do anyway? The thing is for the website it should be looked at on a web server and that can't be done with a commit hook. And no automation can do that either. 

There are some things that can be done without having to look at the website: a fix in a script for instance, but the web pages there would be no gain. But what could GitHub do to improve testing of scripts? I don't know but I also don't know what they can do.

Still if they can do something interesting I'd at least be interested in knowing what .. whether or not it can help us (and eventually just Landon) or not.

**Comment by lcn2** [comment] 2024-07-03 18:54
After sleeping on it, the problem is that things like`make www` (and worse `make update`) do MIUSH more than testing: they build and update things.

However, some of the mini make rules are test only rules such as:

```
make tab_check		 - check for ASCII tabs in markdown files
make genpath		 - form top level .top, YYYY level .year and winner .path files
make genfilelist	 - generate YYYY level .filelist
make verify_entry_files	 - check to be sure all files in all entries exist
make find_missing_links	 - find markdown links to missing local files
```

See commit git a379463919f0a454506354e9e2acb2c7834d34b2 for an introduction to a new top level Makefile rule:

```sh
make test
```

This rule takes about 35 seconds to run.

If all is well, `make test` should **exit 0**, otherwise it will exit non-zero.

# QUESTION

Perhaps `make test` could become the basis of some hook, client or server side wise?

**Comment by xexyl** [comment] 2024-07-03 19:00
> After sleeping on it, the problem is that things like`make www` (and worse `make update`) do MIUSH more than testing: they build and update things.
> 
> However, some of the mini make rules are test only rules such as:
> 
> ```
> make tab_check		 - check for ASCII tabs in markdown files
> make genpath		 - form top level .top, YYYY level .year and winner .path files
> make genfilelist	 - generate YYYY level .filelist
> make verify_entry_files	 - check to be sure all files in all entries exist
> make find_missing_links	 - find markdown links to missing local files
> ```
> 
> See commit git [a379463](https://github.com/ioccc-src/temp-test-ioccc/commit/a379463919f0a454506354e9e2acb2c7834d34b2) for an introduction to a new top level Makefile rule:
> 
> ```shell
> make test
> ```
> 
> This rule takes about 35 seconds to run.
> 
> If all is well, `make test` should **exit 0**, otherwise it will exit non-zero.
> 
> # QUESTION
> Perhaps `make test` could become the basis of some hook, client or server side wise?

Hmm .. I don't know about this at least for a client hook: there are many times when one might not want to do `make clobber`. I know it's necessary for a number of rules but those rules (or scripts) tend to do that already. But that being said for some in `make test` we don't need `make clobber` and one could always introduce the commands individually in a hook.  But as for the server side part.

Another question to consider. Let's say this is server side: what happens if it fails? Should the commit fail or what? Because depending on what happens it would be quite annoying if it means someone has to redo the pull request entirely. I'm not saying it would do this: I really don't know.

**Comment by lcn2** [comment] 2024-07-03 19:12
> Hmm .. I don't know about this at least for a client hook: there are many times when one might not want to do make clobber. I know it's necessary for a number of rules but those rules (or scripts) tend to do that already. But that being said for some in make test we don't need make clobber and one could always introduce the commands individually in a hook. But as for the server side part.

We agree.  This suggests that the workflow might be better on the server side.

> Another question to consider. Let's say this is server side: what happens if it fails? Should the commit fail or what? Because depending on what happens it would be quite annoying if it means someone has to redo the pull request entirely. I'm not saying it would do this: I really don't know.

We accepted [pr 895](https://github.com/ioccc-src/mkiocccentry/pull/895) for the [mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry).  Let's see how we like that and learn from that experience.

# Request to @SirWumpus

As you can see, @SirWumpus, not all skeptical comments turn into a "won't fix" close.  :-)

Please offer an after to @xexyl question:

> Let's say this is server side: what happens if it fails? Should the commit fail or what? 

As a someone uninformed opinion on this matter:   Please offer a pull request for this repo, a server side action that would run the new `make test` rule: something that would block a commit if the `make test` failed, perhaps?

**Comment by lcn2** [comment] 2024-07-03 19:14
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by xexyl** [comment] 2024-07-03 19:15
> > Hmm .. I don't know about this at least for a client hook: there are many times when one might not want to do make clobber. I know it's necessary for a number of rules but those rules (or scripts) tend to do that already. But that being said for some in make test we don't need make clobber and one could always introduce the commands individually in a hook. But as for the server side part.
> 
> We agree. This suggests that the workflow might be better on the server side.
> 

I'm glad you agree.

> > Another question to consider. Let's say this is server side: what happens if it fails? Should the commit fail or what? Because depending on what happens it would be quite annoying if it means someone has to redo the pull request entirely. I'm not saying it would do this: I really don't know.
> 
> We accepted [pr 895](https://github.com/ioccc-src/mkiocccentry/pull/895) for the [mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry). Let's see how we like that and learn from that experience.
> 

Sounds like a good idea. Maybe before this one (but see my below thoughts)?

> # Request to @SirWumpus
> As you can see, @SirWumpus, not all skeptical comments turn into a "won't fix" close. :-)
> 
> Please offer an after to @xexyl question:
> 
> > Let's say this is server side: what happens if it fails? Should the commit fail or what?
> 
> As a someone uninformed opinion on this matter: Please offer a pull request for this repo, a server side action that would run the new `make test` rule: something that would block a commit if the `make test` failed, perhaps?

Okay but what do you mean by 'block the commit'? I wonder if this is a good idea. We can always fix the problem but mistakes can happen from time to time. This has a potential to discourage people for (in this case) little gain. Though of course there are different definitions of 'block'.

**Comment by lcn2** [comment] 2024-07-03 19:20
> > As a someone uninformed opinion on this matter:  ...
>
> Okay but what do you mean by 'block the commit'? I wonder if this is a good idea. We can always fix the problem but mistakes can happen from time to time. This has a potential to discourage people for (in this case) little gain. Though of course there are different definitions of 'block'.

We do not know (thus our "As a someone uninformed opinion on this matter:" remark 🤓).   Let us see what @SirWumpus suggests and replies with, @xexyl .

**Comment by xexyl** [comment] 2024-07-03 19:21
> > > As a someone uninformed opinion on this matter:  ...
> > 
> > 
> > Okay but what do you mean by 'block the commit'? I wonder if this is a good idea. We can always fix the problem but mistakes can happen from time to time. This has a potential to discourage people for (in this case) little gain. Though of course there are different definitions of 'block'.
> 
> We do not know (thus our "As a someone uninformed opinion on this matter:" remark 🤓). Let us see what @SirWumpus suggests and replies with, @xexyl .

Yes ... I just wanted to raise that as another potential problem - not expecting you to answer. But thanks (in case)!

**Comment by SirWumpus** [comment] 2024-07-03 19:46
Sorry.  Just finished 1h20m interview with FreeBSD Foundation for a position.  Mind has been racing.

* If you have a `pre-commit` hook that returns non-zero (and you did not given `-n`) then that local commit fails.

* If you have a pull-request that fails, I think the merge is aborted, the pull-request left open to be fixed.

* For a git push the commit has already been made (hopefully with a pre-commit hook validation).  The push will succeed, but the `Actions` will show a failed CI run.  In which case additional fixes need be made and pushed until the CI run passes.

DOes that cover it?  Did I miss other questions?

**Comment by SirWumpus** [comment] 2024-07-03 19:49
Since everyone tends to work on their own forks instead of branches of the main repo, if a failure happens on a fork, then you typically don't submit a pull-request until resolved.

**Comment by xexyl** [comment] 2024-07-03 19:52
> Sorry. Just finished 1h20m interview with FreeBSD Foundation for a position. Mind has been racing.
> 
> * If you have a `pre-commit` hook that returns non-zero (and you did not given `-n`) then that local commit fails.
> * If you have a pull-request that fails, I think the merge is aborted, the pull-request left open to be fixed.
> * For a git push the commit has already been made (hopefully with a pre-commit hook validation).  The push will succeed, but the `Actions` will show a failed CI run.  In which case additional fixes need be made and pushed until the CI run passes.
> 
> DOes that cover it? Did I miss other questions?

I knew the first one. Can we verify the second one? Even so I wonder if in this case it's a good idea .. it's easy to fix problems here and it might be more encouraging to not have this here. The other one is something else as it's code that has to be stable but here it's just a website and errors can be fixed easily enough.

But if that's not decided to be the way to go: as long as the pull request can be fixed it seems good. I guess we might be able to determine that with the other repo?

**Comment by SirWumpus** [comment] 2024-07-03 20:01
> * If you have a pull-request that fails, I think the merge is aborted, the pull-request left open to be fixed.

In the case of an error.  It probably more likely that the pull-request will be merged (option?), but that the CI run fail, but otherwise does not impede anyone using the main repo.  It will just have an annoying niggle about CI fun fail.

**Comment by SirWumpus** [comment] 2024-07-03 20:02
I don't like annoying niggles.

**Comment by lcn2** [comment] 2024-07-03 20:40
> Since everyone tends to work on their own forks instead of branches of the main repo, if a failure happens on a fork, then you typically don't submit a pull-request until resolved.

We typically work on the master.  Is that a bad thing?

**Comment by SirWumpus** [comment] 2024-07-03 20:57
Oh my!  Well...

I've only done it three ways (git that is).

* Personal projects I work directly on a branch then merge/rebase to master/main before pushing to my repos.  In recent years I try to avoid working directly on main (breaking bad habits).

* Last place of work, you would have a master branch typically controlled access, a develop branch, and ticket / feature branches from the develop branch.  Devs worked on their branches, submit pull-request for code review if they can, and merge to develop.  Later when cutting a release team lead would merge develop to main, tag, release etc.  So master is what is currently in production, develop is collection of fixes and features for next release and smaller individual developer branches for the tickets.  This might have been more a GitLab workflow thing, but with teams its good.

* Alternative which I hadn't tried till this stuff is take a fork, work on your own branches or main, and then submit your pull requests from the fork.  I wasn't sure I had write access to your repo, so this seemed best way to work without risking main.  As you might have noticed from my pull-requests, I did my changes still off of a branch on my fork, so I could revert easily to sane state if needed.  Later I would re-sync from the main repo to pick up everyone else's changes.

I can't say I know a lot about the various work flows for teams, but these seem popular.

**Comment by SirWumpus** [comment] 2024-07-03 21:18
Not sure you need worry, unless you feel the current process needs a little more discipline, especially if there are future contributors.

**Comment by xexyl** [comment] 2024-07-04 01:12
> Not sure you need worry, unless you feel the current process needs a little more discipline, especially if there are future contributors.
> 
> 

My guess as well. I always work on the master branch of my repos too. Though most of mine are private and on my server and not GitHub. 

But I don't know much about the workflows that were brought up here. 

I will reply to other comments tomorrow (I think you replied to me). Off to get some sleep. Knackered. 

Weather doesn't help. We (completely unsurprising) have at least one fire in the city right now. All day there have been helicopters flying over to help. It was doing my head in but when I found out about the fire it makes it understandable even if I don't like to hear it. 

It's cooling down. Only 29 now. But humidity is high for here. 43%. Just hope the power doesn't go out. 

Hope the weather is better for you both than what it is here .. and we're just starting of course. 

Good night! Thanks for the help! Cheers.

**Comment by lcn2** [comment] 2024-07-05 01:33
With commit a72cff909f23dd88ddfb880a80e7db5acc9d3ea6 we added `.github/workflows/test.yml` and so this issue has been resolved.

**Closed by lcn2** 2024-07-05 01:33 UTC
Labels: enhancement

**Comment by xexyl** [comment] 2024-07-05 13:01
Okay I just looked at the process on a commit I made and it makes me think: the fact there is verbosity that is written to `/dev/null` for these tests when we want to be aware of problems - is that the right way to go about it? Perhaps there should be an update to the Makefile that the workflow script will run that will not suppress the detailed information?

If you think that's a good idea I'd be happy to do that for you. What do you think?

The commit I did was a slight guidelines update to make something a bit clearer ... though as said before I think they're in pretty good shape and probably I don't need to do any more on them unless you'd like me to take a look after you do a final update. ... going back to the less obfuscated versions now. If I can get that done today it's more than I was hoping for and I think I will be able to though soon I'll have to go afk for a while. The first one went very quickly though so I don't see why I couldn't do the others just as quickly.
